### PR TITLE
edhoc/messages/base: fix decode_bstr_id for non int

### PR DESCRIPTION
**Pull request by fjmolinas**
Current code would error if a byte string is used as conn_id, this fixse it.

### CODE REVIEW

**Comment by fjmolinas** [comment]
@malishav @TimothyClaeys  ping

**Comment by fjmolinas** [comment]
ping @TimothyClaeys!

**Comment by fjmolinas** [comment]
ping @malishav @TimothyClaeys :)

**Comment by malishav** [comment]
@TimothyClaeys unless you object, I propose we go ahead and merge this PR.

**Pull request merged**
