### PR TITLE
Adapt to EDHOC draft -05

### PR DESCRIPTION
**Pull request by chrysn**
This is based on #8, so please ignore the earlier commits (which GitHub just doesn't manage to hide as "from other branch").

This is incomplete as the test suite's vectors are not adjusted -- but then again I haven't manage to run the tests yet. (`python3 -m unittest` and `python3 setup.py test` didn't run any tests, `python3 -m test` didn't terminate).

### CODE REVIEW

**Comment by chrysn** [comment]
There's a bit of not-sure-if-related commits accumulating here; I'll report back when I have a better picture and tests.

**Comment by chrysn** [comment]
I've slimmed this down to what's actually necessary to make -05 work; the rest will probably focus around _parse_credentials fixes (to make them work with callbacks in the first place, and then work flexibly).

What's remaining is rebuilding the test vectors, so far jumping around manually there to see what actually needs to be changed.

**Comment by TimothyClaeys** [comment]
Ok, I'll first fix these conflicts and update the test vectors. I've just updated the code to use the new pycose API. I was also thinking of accepting the credentials either as a [COSE key object](url) (https://github.com/TimothyClaeys/pycose/blob/master/cose/keys/cosekey.py) or as a `Certificate` object from the asn1crypto module.

**Comment by chrysn** [comment]
Ah, and I was wondering why conflicts were showing up on something that I just only now rebased onto master :-)

Fine, then I'll leave my hands off this for a moment and continue on other construction sites; let me know when there's anything I can continue on here.

**Comment by TimothyClaeys** [comment]
Ok, perfect !

**Comment by chrysn** [comment]
As for passing around things, I'm all for using full objects here (as this gives the application flexibility and doesn't force things to be encoded and decoded back and forth).

Concerning the certificates, it may make sense to have some way to keep them custom. Then again, they can all duck-type into behaving like a CoseKey by providing an encode() function and a verify() function.

**Comment by TimothyClaeys** [comment]
I checked out this branch and resolved the conflicts locally. However when I try to push the commits to this PR, I get an access denied. Any ideas how to solve this?

**Comment by chrysn** [comment]
There's some feature in GitHub that allows this, but I'm not familiar with it -- I try to stick with the simpler original git workflows. It's probably easiest if you just push your branch to this repo (rather than pushing onto mine), wait for CI to run through that if need be, merge that and reject this one.

**Comment by TimothyClaeys** [comment]
Commits were included in PR #14

**Comment by chrysn** [comment]
Thanks! Rebasing the rest of my stuff.

**Pull request closed without merging**
